#cloud-config
# spam4kev@gmail.com 2/22/16
users:
  - default
  - name: spam4kev
    gecos: kev
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    ssh-import-id: None
    lock-passwd: true
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRKqdKKEuOCc+h+oagKolmH11AOrODDCCYBqgWz0ouVr2FTNelevM3J2e+ym/prE4Js/5yOyUPwz23LgiSEM5JNnGhJPSgpIU7NwybNDHe7q7Xa5aRoIoJ+d7ls21Kp0ZUnQxroTM0NOl/5hv1i0HHI8/WtMLNCbOqoGJQIfOO6mqRTxWtCpXzskPeL7R8HAM0wty+HJ+aF3B/RBJKHWpU6m5t1LXuiqDLlCtFUfFp20E9SJbTkf9+kiX5XlTSRcOkex0OTyiK/jfVIRKuyytZPP7/BV/Hvy1DyIcgRLyoKRPuuLwpp9elcE4CHLp1TnCwR6XkBrrZAlcZdddozTWB imported-openssh-key

runcmd:
 - dhclient
 - yum update -y
 - yum install bind -y
 - systemctl enable named
 - systemctl start named

